<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Automatically generate routes from CommercantsController
Route::resource('commercants', 'CommercantsController');

// Home page
Route::get('/', function () {
    return view('welcome');
});

// Routes generated by Voyager
Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});
